weights: ''
cfg: cfg/yolov7-w6-pose-mod2.yaml
data: data/coco_kpts.yaml
hyp: data/hyp.pose.yaml
epochs: 300
batch_size: 8
img_size:
- 960
- 960
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: true
adam: false
sync_bn: true
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov7-w6-pose-mod-new-2nd
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: 20
artifact_alias: latest
kpt_label: true
world_size: 1
global_rank: -1
save_dir: runs/train/yolov7-w6-pose-mod-new-2nd13
total_batch_size: 8
